site_name: bring
repo_url: https://gitlab.com/frkl/bring
theme:
  name: material
  palette:
   scheme: default
site_author: Markus Binsteiner
docs_dir: docs
site_dir: build/site

markdown_extensions:
- attr_list
- admonition
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.snippets:
    base_path: docs
- pymdownx.highlight:
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.superfences

nav:
- Home: index.md
- Install: install.md
- Quickstart: quick-start.md
- Usage: usage/getting-started.md
- API Documentation: api-documentation.md
plugins:
- search
- macros:
   module_name: ci.docs
extra_css:
  - stylesheets/extra.css
