name: build binaries
# This workflow is triggered on pushes to the repository.
on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_10.3.app/Contents/Developer
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  test-darwin:
    name: pytest on darwin
    runs-on: macos-latest
    steps:
      - name: Set up Python 3.7.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
      - uses: actions/checkout@v2
      - run: pip install -e '.[testing]'
      - name: Test with pytest
        run: pytest tests

  build-darwin:
    name: build darwin binary
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.pyenv/
          key: ${{ runner.os }}-target-10.11-bring-python-build
      - run: brew install pyenv
      - run: brew install pyenv-virtualenv
      - uses: actions/checkout@v2
      - name: pyinstaller
        run: ./binary_build/build.sh --spec-file binary_build/onefile.spec
      - name: find
        run: find .
      - name: ls
        run: ls -lah
      - name: pwd
        run: pwd
      - name: Add MacOS certs
        run: chmod +x deploy/add-osx-cert.sh && ./deploy/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: sign binary
        run: "codesign -f -s 'Developer ID Application: Markus Binsteiner (4Q559SZWTL)' dist/darwin19/bring"
      - name: Archive Mac OS X binary
        uses: actions/upload-artifact@v1
        with:
          name: bring
          path: dist/darwin19/bring
