name: build binaries
# This workflow is triggered on pushes to the repository.
on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_9.4.1.app/Contents/Developer

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.pyenv/
          key: ${{ runner.os }}-9.4.1-bring-python
      - run: brew install pyenv
      - run: brew install pyenv-virtualenv
      - uses: actions/checkout@v2
      - name: pyinstaller
        run: ./binary_build/build.sh --spec-file binary_build/onefile.spec
      - name: find
        run: find .
      - name: ls
        run: ls -lah
      - name: pwd
        run: pwd
      - name: Add MacOS certs
        run: chmod +x deploy/add-osx-cert.sh && ./deploy/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: sign binary
        run: "codesign -f -s 'Developer ID Application: Markus Binsteiner (4Q559SZWTL)' dist/darwin19/bring"
      - name: Archive Mac OS X binary
        uses: actions/upload-artifact@v1
        with:
          name: bring
          path: dist/darwin19/bring
