name: build binaries
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.pyenv/
          key: ${{ runner.os }}-bring-pythone
      - run: brew install pyenv
      - run: brew install pyenv-virtualenv
      - uses: actions/checkout@v2
      - name: pyinstaller
        run: ./binary_build/build.sh --spec-file binary_build/onefile.spec
      - name: Add MacOS certs
        if: matrix.os == 'macos-latest'
        run: chmod +x deploy/add-osx-cert.sh && ./deploy/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
