name: build binaries
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v5
      - name: pyinstaller
        run: ./binary_build/build.sh --spec-file binary_build/onefile.spec
